



env:
  AUTH_TOKEN: ""
  HARBOR_ID: ""
  SHIP_ID: ""
  DOCKER_REGISTRY: "gcr.io/verdant-bulwark-278"
  AUTO_KUBERNETES_UPDATE: "true"

imageRegistry: "gcr.io/verdant-bulwark-278/blazemeter/"
dockerTag: "latest-master"
pullPolicy: "Always"