
deployment:
  name: crane
  namespace: bm

matches:
  crane: ready
  role: role-crane

serviceAccount: default

env:
  auth_token: ""
  harbour_id: ""
  ship_id: ""
  docker_regirstry: "gcr.io/verdant-bulwark-278"
  auto_update: "true"
  imageRegistry: "gcr.io/verdant-bulwark-278/blazemeter/"
  dockerTag: "latest-master"
  pullPolicy: "Always"

restartPolicy: Always