
deployment:
  name: crane
  namespace: "bm"

matches:
  crane: "ready"
  role: "role-crane"
  clusterrole: "cluster-role-crane"

serviceAccount:
  # Specifies whether a ServiceAccount should be created, currently BM OPLs in Kubernetes only supports default service account.
  create: false
  # The name of the ServiceAccount to use, keep empty to use default account.
  name: 

env:
  authtoken: "sfbwig"
  harbour_id: "lkndvoehrgo"
  ship_id: "kjdf2397rknfdl"
  docker_regirstry: "gcr.io/verdant-bulwark-278"
  auto_update: "'true'"
  image: "gcr.io/verdant-bulwark-278/blazemeter/crane:latest-master"
  pullPolicy: "Always"

  # Proxy configurations here
proxy:
  http_proxy: no
  https_proxy: no
 # If you have authentication required for your proxy, then you will need to add username:password@server:port
  proxy_path: "http://server:port" 
#  the NO_PROXY settings for 127.0.0.1 and localhost (provided below) are required for the Service Virtualization integration and 
#  Transaction-based Mock Services to work. If you do not use any HTTP_PROXY or HTTPS_PROXY settings, you can skip the NO_PROXY setting.
  no_proxy: "kubernetes.default,127.0.0.1,localhost,myHostname.com"


restartPolicy: "Always"