{{ if and (.Values.istio_ingress.enable)  (eq .Values.nginx_ingress.enable false) }} 
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.istio_ingress.istio_gateway_name }}
  namespace : {{ .Values.deployment.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-80
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: https-443
      protocol: HTTPS
    hosts:
    - "*"      
    tls:
      mode: SIMPLE
      # This must be located in the "istio-system" namespace
      credentialName: {{ .Values.istio_ingress.credentialName }}
  - port:
      number: 15443
      name: https-15443
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: PASSTHROUGH
{{ end }}
