{{ if and (.Values.istio_ingress.use)  (eq .Values.nginx_ingress.use false) }} 
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.istio_ingress.istio_gateway_name }}
  namespace : {{ .Values.deployment.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-80
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: https-443
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "*"
  - port:
      number: 15443
      name: https-15443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.istio_ingress.credentialName }}
    hosts:
    - "*"
{{ end }}