{{ if or ( .Values.ca_bundle.enable | default false  ) ( .Values.gridProxy.enable | default false ) }} 
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  {{ if  .Values.ca_bundle.enable }} 
  {{ .Values.ca_bundle.request_ca_bundle }}: |-
{{ .Files.Get .Values.ca_bundle.request_ca_bundle | indent 4 }}
  {{ .Values.ca_bundle.aws_ca_bundle }}: |-
{{ .Files.Get .Values.ca_bundle.aws_ca_bundle | indent 4 }}
  {{ end -}}
  {{ if  .Values.gridProxy.enable }} 
  {{ .Values.gridProxy.tlsKeyGrid }}: |-
{{ .Files.Get .Values.gridProxy.tlsKeyGrid | indent 4 }}
  {{ .Values.gridProxy.tlsCertGrid }}: |-
{{ .Files.Get .Values.gridProxy.tlsCertGrid | indent 4 }}
  {{ end -}}
{{ end -}}