{{ if .Values.ca_bundle.use }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: bm
data:
  certificate.crt: |-
    {{ .Files.Get "certificate.crt" | indent 4 }}
{{ end }}
