apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: {{ .Values.matches.role }}
  name: {{ .Release.name }}_crane
  namespace: {{ .Values.deployment.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      role: {{ .Values.matches.role }}
      crane: {{ .Values.matches.crane }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        role: {{ .Values.matches.role }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: crane
                operator: In
                values:
                - {{ .Values.matches.crane }}

      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: true
      containers:
      - env:
        - name: AUTH_TOKEN
          value: {{ .Values.env.authtoken }}
        - name: HARBOR_ID
          value: {{ .Values.env.harbour_id }}
        - name: SHIP_ID
          value: {{ .Values.env.ship_id }}
        - name: CONTAINER_MANAGER_TYPE
          value: KUBERNETES
        - name: IMAGE_OVERRIDES
          value: '{}'
        - name: DOCKER_REGISTRY
          value: {{ .Values.env.docker_regirstry }}
        - name: AUTO_KUBERNETES_UPDATE
          value: {{ .Values.env.auto_update }}

          {{- if .Values.proxy.http_proxy }}
        - name: HTTP_PROXY
          value: {{ .Values.proxy.proxy_path }}    
        - name: NO_PROXY
          value: {{ .Values.proxy.no_proxy }} 

          {{- else if .Values.proxy.https_proxy }}
        - name: HTTPS_PROXY
          value: {{ .Values.proxy.proxy_path }} 
        - name: NO_PROXY
          value: {{ .Values.proxy.no_proxy }}     
          {{- end }}
        
        image: {{ .Values.env.image }} 
        imagePullPolicy: {{ .Values.env.pullPolicy }}
        name: crane-container
      restartPolicy: {{ .Values.restartPolicy }}
      terminationGracePeriodSeconds: 30