apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: {{ .Values.matches.role }}
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      role: {{ .Values.matches.role }}
      crane: {{ .Values.matches.crane }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        role: {{ .Values.matches.role }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: crane
                operator: In
                values:
                - {{ .Values.matches.crane }}

      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: true
      containers:
      - env:
        - name: AUTH_TOKEN
          value: 
        - name: HARBOR_ID
          value: 
        - name: SHIP_ID
          value: 
        - name: CONTAINER_MANAGER_TYPE
          value: KUBERNETES
        - name: IMAGE_OVERRIDES
          value: '{}'
        - name: DOCKER_REGISTRY
          value: {{ .Value.env.docker_regirstry }}
        - name: AUTO_KUBERNETES_UPDATE
          value: 'true'
        image: {{ .Value.env.image }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: crane-container
      restartPolicy: Always
      terminationGracePeriodSeconds: 30