apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Values.deployment.clusterrole }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "update", "watch", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-{{ .Values.deployment.clusterrole }}-binding-{{ template "blazemeter-crane.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ .Values.deployment.clusterrole }}
subjects:
- kind: ServiceAccount
  name: {{ template "blazemeter-crane.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
