{{ if not .Values.deployment.role }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "crane.roleName" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "list", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["extensions", "apps", "batch", ""] # leave empty string for core
  resources: ["pods", "services", "endpoints", "daemonsets", "pods/*", "pods/exec", "deployments", "replicasets", "ingresses", "deployments/scale", "jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection", "createcollection"]
{{ if  eq .Values.service_virtualization.ingressType "istio" }}
# this is for istio ingress mock services deployment
- apiGroups: ["networking.istio.io"]
  resources: ["destinationrules", "virtualservices", "gateways"]
  verbs: ["get", "list", "create", "delete", "patch", "update"]
{{ else if eq .Values.service_virtualization.ingressType "nginx" }}
# this is for nginx ingress mock services deployment
- apiGroups: ["networking.k8s.io"]
  resources: ["virtualservices", "gateways", "ingresses"]
  verbs: ["get", "list", "create", "delete", "patch", "update"]
{{ end }}
---
{{ end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "crane.roleName" . }}binding-{{ template "blazemeter-crane.serviceAccountName" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "blazemeter-crane.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role 
  name: {{ include "crane.roleName" . }}
  apiGroup: rbac.authorization.k8s.io