apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.matches.role }}
  namespace: {{ .Values.deployment.namespace }}
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["extensions", "apps", "batch", ""] # leave empty string for core
  resources: ["pods", "services", "endpoints", "daemonsets", "pods/*", "pods/exec", "deployments", "replicasets", "ingresses", "deployments/scale", "jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection", "createcollection"]
{{ if and (.Values.istio_ingress.use)  (eq .Values.nginx_ingress.use false) }} 
# this is for istio ingress mock services deployment
- apiGroups: ["networking.istio.io"]
  resources: ["destinationrules", "virtualservices", "gateways"]
  verbs: ["get", "list", "create", "delete", "patch", "update"]
{{- end -}}
{{ if and (.Values.nginx_ingress.use)  (eq .Values.istio_ingress.use false)}}
# this is for nginx ingress mock services deployment
- apiGroups: ["networking.k8s.io"]
  resources: ["virtualservices", "gateways", "ingresses"]
  verbs: ["get", "list", "create", "delete", "patch", "update"]
{{ end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.matches.role }}-binding-{{ .Values.deployment.namespace }}-{{ template "blazemeter-crane.serviceAccountName" . }}
  namespace: {{ .Values.deployment.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "blazemeter-crane.serviceAccountName" . }}
  namespace: {{ .Values.deployment.namespace }}
roleRef:
  kind: Role 
  name: {{ .Values.matches.role }}
  apiGroup: rbac.authorization.k8s.io