{{- if not .Values.deployment.clusterrole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "crane.clusterroleName" . }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "update", "watch", "patch" ]
---
{{ end }}
{{ if not .Values.deployment.ignoreBindings | default false }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "crane.clusterroleName" . }}binding-{{ template "blazemeter-crane.serviceAccountName" . }}-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "crane.clusterroleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "blazemeter-crane.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}