{{ if .Values.secretProviderClass.enable }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets-store
  namespace: {{ .Release.Namespace }}
spec:
  parameters:
    objects: |
      {{ .Values.secretProviderClass.objects | toYaml | nindent 6 }}
  provider: {{ .Values.secretProviderClass.provider }}
  {{ if .Values.secretProviderClass.secretObjects }}
  secretObjects:
    {{- range .Values.secretProviderClass.secretObjects }}
    - secretName: {{ .secretName }}
      type: {{ .type }}
      data:
        {{- range .data }}
        - key: {{ .key }}
          objectName: {{ .objectName }}
        {{- end }}
    {{- end }}
  {{ end }}
{{ end }}