{{ if and (.Values.secretProviderClass.enable) (not .Values.externalSecretsOperator.enable) }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets-store
  namespace: {{ .Release.Namespace }}
spec:
  parameters:
    objects: |
      {{ .Values.secretProviderClass.objects | toYaml | nindent 6 }}
  provider: {{ .Values.secretProviderClass.provider }}
  {{ if .Values.secretProviderClass.secretObjects }}
  secretObjects:
    {{- range .Values.secretProviderClass.secretObjects }}
    - secretName: {{ .secretName }}
      type: {{ .type }}
      data:
        {{- range .data }}
        - key: {{ .key }}
          objectName: {{ .objectName }}
        {{- end }}
    {{- end }}
  {{ end }}
{{ end }}
{{ if and (.Values.externalSecretsOperator.enable) (not .Values.secretProviderClass.enable) }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
{{ with .Values.externalSecretsOperator.secretStore }}
metadata:
  name: {{ .name }}  
  namespace: {{ $.Release.Namespace }}
spec:
  {{ with .provider }}
  provider: 
    {{ if and ( .aws.enable ) (not .gcpsm.enable ) }}
    aws:
      service: {{ .aws.service }}
      region: {{ .aws.region }}
      auth:
      {{ if not .aws.authSecretRef.enable }}
        jwt:
          serviceAccountRef:
            name: {{ template "blazemeter-crane.serviceAccountName" $ }}
            namespace: {{ $.Release.Namespace }}
      {{ else }}
        secretRef:
          accessKeyID:
            name: {{ .aws.authSecretRef.accessKeyID.name }}
            key: {{ .aws.authSecretRef.accessKeyID.key }}
          secretAccessKey:
            name: {{ .aws.authSecretRef.secretAccessKey.name }}
            key: {{ .aws.authSecretRef.secretAccessKey.key }}
      {{ end }}
    {{ else if and (.gcpsm.enable) (not .aws.enable) }}
    gcpsm:
      projectID: {{ .gcpsm.projectID }}
      auth:
      {{ if not .gcpsm.authSecretRef.enable }}
        workloadIdentity:
          serviceAccountRef:
            name: {{ template "blazemeter-crane.serviceAccountName" $ }}
            namespace: {{ $.Release.Namespace }}
      {{ else }}
        secretRef:
          secretKeyRef:
            name: {{ .gcpsm.authSecretRef.name }}
            key: {{ .gcpsm.authSecretRef.key }}
      {{ end }}
    {{ else }}
      {{ fail "Either AWS or gcpsm provider must be enabled, not both." }}
    {{ end }}  
  {{ end }}
{{ end }}
--- 
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  {{ with .Values.externalSecretsOperator }}
  name: {{ .externalSecret.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: {{ .externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .secretStore.name }} # Reference the SecretStore
    kind: SecretStore
  target:
    name: {{ .externalSecret.target }} # Name of Kubernetes Secret to make
  data:
    {{ range .externalSecret.data }}
    - secretKey: {{ .secretKey }} # New key to make
      remoteRef:
        key: {{ .remoteRef.key }} # Name of the Secret in Secrets Manager
    {{ end }}    
  {{ end }}  
{{ end }}