{{ if .Values.deployment.serviceAccount.create | default false}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blazemeter-crane.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{ if .Values.deployment.serviceAccount.annotations | default false}}
  annotations:
    {{- with .Values.deployment.serviceAccount.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{ end }}
  labels:
    role: {{ include "crane.roleName" . }}
    clusterrole: {{ include "crane.clusterroleName" . }}
{{ end }}
